-- Create mindmaps table for storing AI-generated mind maps
-- This table stores mermaid diagram code generated by Gemini 2.5 Flash

-- 1. Create mindmaps table
CREATE TABLE IF NOT EXISTS mindmaps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  content_mermaid TEXT NOT NULL, -- Mermaid diagram code (mindmap or graph TD)
  source_ids JSONB, -- Array of source IDs used to generate this mindmap
  tipo TEXT DEFAULT 'standard', -- 'standard' or 'recovery' (from difficulties)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_mindmaps_project_id ON mindmaps(project_id);
CREATE INDEX IF NOT EXISTS idx_mindmaps_user_id ON mindmaps(user_id);
CREATE INDEX IF NOT EXISTS idx_mindmaps_tipo ON mindmaps(tipo);
CREATE INDEX IF NOT EXISTS idx_mindmaps_created_at ON mindmaps(created_at DESC);

-- 3. Enable Row Level Security
ALTER TABLE mindmaps ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies
-- Policy: Users can view their own mindmaps
CREATE POLICY "Users can view their own mindmaps"
  ON mindmaps
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own mindmaps
CREATE POLICY "Users can insert their own mindmaps"
  ON mindmaps
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own mindmaps
CREATE POLICY "Users can update their own mindmaps"
  ON mindmaps
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own mindmaps
CREATE POLICY "Users can delete their own mindmaps"
  ON mindmaps
  FOR DELETE
  USING (auth.uid() = user_id);

-- 5. Add comments for documentation
COMMENT ON TABLE mindmaps IS 'Stores AI-generated mind maps in Mermaid diagram format';
COMMENT ON COLUMN mindmaps.content_mermaid IS 'Mermaid diagram code - can be mindmap or graph TD syntax';
COMMENT ON COLUMN mindmaps.tipo IS 'Type of mindmap: standard (from normal sources) or recovery (from difficulties analysis)';
COMMENT ON COLUMN mindmaps.source_ids IS 'JSON array of source UUIDs used to generate this mindmap';
